name: todo_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  calendar_timeline: ^1.1.2
  flutter_slidable: ^3.0.0
  firebase_core: ^2.17.0
  cloud_functions: ^4.4.2
  cloud_firestore: ^4.9.3
  intl: ^0.18.1
  firebase_auth: ^4.10.1
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
