// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZG5eDzKHZDXkrdxI06IQN48AyWWyg7Mg',
    appId: '1:525563508874:web:d3e793bf283f6b9552d573',
    messagingSenderId: '525563508874',
    projectId: 'todoapp-6795c',
    authDomain: 'todoapp-6795c.firebaseapp.com',
    storageBucket: 'todoapp-6795c.appspot.com',
    measurementId: 'G-H8V3T4ZTCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNia1hBu5cqcM3JQ0t2dU77-YXDZpQFJ4',
    appId: '1:525563508874:android:91b9d93f51318ce452d573',
    messagingSenderId: '525563508874',
    projectId: 'todoapp-6795c',
    storageBucket: 'todoapp-6795c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtpZ2XE0vEfA6kwjjgR6Awu8eZu9da8ko',
    appId: '1:525563508874:ios:32f68ee0850a802652d573',
    messagingSenderId: '525563508874',
    projectId: 'todoapp-6795c',
    storageBucket: 'todoapp-6795c.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtpZ2XE0vEfA6kwjjgR6Awu8eZu9da8ko',
    appId: '1:525563508874:ios:c48a7d3fb516360e52d573',
    messagingSenderId: '525563508874',
    projectId: 'todoapp-6795c',
    storageBucket: 'todoapp-6795c.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
